server:
  port: 5001
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  application:
    name: ms-oficinas-api

# swagger-ui custom path
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html2