spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/msoficinasdb
    username: postgres
    password: 102030
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  rabbitmq:
    host: localhost
    port: 5672
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}

api:
  security:
    secret: ${security.secret}
#app:
#  consumidor:
#    urls: http://localhost:9000
